// {"simbolo":"","noAtomico":"","nombre":"","masa":""},
var tablaper=[
{"noAtomico":"1","nombre":"Hidrógeno","simbolo":"H","masa":"1.0079","metal":"Otros no metales"},
{"noAtomico":"2","nombre":"Helio","simbolo":"He","masa":"4.0026","metal":"Gases nobles"},
{"noAtomico":"3","nombre":"Litio","simbolo":"Li","masa":"6.941","metal":"Alcalinos"},
{"noAtomico":"4","nombre":"Berilio","simbolo":"Be","masa":"9.0122","metal":"Alcalinotérreos"},
{"noAtomico":"5","nombre":"Boro","simbolo":"B","masa":"10.811","metal":"Metaloides"},
{"noAtomico":"6","nombre":"Carbono","simbolo":"C","masa":"12.0107","metal":"Otros no metales"},
{"noAtomico":"7","nombre":"Nitrógeno","simbolo":"N","masa":"14.0067","metal":"Otros no metales"},
{"noAtomico":"8","nombre":"Oxígeno","simbolo":"O","masa":"15.9994","metal":"Otros no metales"},
{"noAtomico":"9","nombre":"Fluor","simbolo":"F","masa":"18.9984","metal":"Halógenos"},
{"noAtomico":"10","nombre":"Neón","simbolo":"Ne","masa":"20.1797","metal":"Gases nobles"},
{"noAtomico":"11","nombre":"Sodio","simbolo":"Na","masa":"22.9897","metal":"Alcalinos"},
{"noAtomico":"12","nombre":"Magnesio","simbolo":"Mg","masa":"24.305","metal":"Alcalinotérreos"},
{"noAtomico":"13","nombre":"Aluminio","simbolo":"Al","masa":"26.9815","metal":"Metales del bloque p"},
{"noAtomico":"14","nombre":"Sílice","simbolo":"Si","masa":"28.0855","metal":"Metaloides"},
{"noAtomico":"15","nombre":"Fósforo","simbolo":"P","masa":"30.9738","metal":"Otros no metales"},
{"noAtomico":"16","nombre":"Azufre","simbolo":"S","masa":"32.065","metal":"Otros no metales"},
{"noAtomico":"17","nombre":"Cloro","simbolo":"Cl","masa":"35.453","metal":"Halógenos"},
{"noAtomico":"18","nombre":"Argón","simbolo":"Ar","masa":"39.948","metal":"Gases nobles"},
{"noAtomico":"19","nombre":"Potasio","simbolo":"K","masa":"39.0983","metal":"Alcalinos"},
{"noAtomico":"20","nombre":"Calcio","simbolo":"Ca","masa":"40.078","metal":"Alcalinotérreos"},
{"noAtomico":"21","nombre":"Escandio","simbolo":"Sc","masa":"44.9559","metal":"Metales de transición"},
{"noAtomico":"22","nombre":"Titanio","simbolo":"Ti","masa":"47.867","metal":"Metales de transición"},
{"noAtomico":"23","nombre":"Vanadio","simbolo":"V","masa":"50.9415","metal":"Metales de transición"},
{"noAtomico":"24","nombre":"Cromo","simbolo":"Cr","masa":"51.9961","metal":"Metales de transición"},
{"noAtomico":"25","nombre":"Manganeso","simbolo":"Mn","masa":"54.938","metal":"Metales de transición"},
{"noAtomico":"26","nombre":"Hierro","simbolo":"Fe","masa":"55.845","metal":"Metales de transición"},
{"noAtomico":"27","nombre":"Cobalto","simbolo":"Co","masa":"58.6934","metal":"Metales de transición"},
{"noAtomico":"28","nombre":"Níquel","simbolo":"Ni","masa":"58.9332","metal":"Metales de transición"},
{"noAtomico":"29","nombre":"Cobre","simbolo":"Cu","masa":"63.546","metal":"Metales de transición"},
{"noAtomico":"30","nombre":"Zinc","simbolo":"Zn","masa":"65.39","metal":"Metales de transición"},
{"noAtomico":"31","nombre":"Galio","simbolo":"Ga","masa":"69.723","metal":"Metales del bloque p"},
{"noAtomico":"32","nombre":"Germanio","simbolo":"Ge","masa":"72.64","metal":"Metaloides"},
{"noAtomico":"33","nombre":"Arsénico","simbolo":"As","masa":"74.9216","metal":"Metaloides"},
{"noAtomico":"34","nombre":"Selenio","simbolo":"Se","masa":"78.96","metal":"Otros no metales"},
{"noAtomico":"35","nombre":"Bromo","simbolo":"Br","masa":"79.904","metal":"Halógenos"},
{"noAtomico":"36","nombre":"Kryptón","simbolo":"Kr","masa":"83.8","metal":"Gases nobles"},
{"noAtomico":"37","nombre":"Rubidio","simbolo":"Rb","masa":"85.4678","metal":"Alcalinos"},
{"noAtomico":"38","nombre":"Estroncio","simbolo":"Sr","masa":"87.62","metal":"Alcalinotérreos"},
{"noAtomico":"39","nombre":"Itrio","simbolo":"Y","masa":"88.9059","metal":"Metales de transición"},
{"noAtomico":"40","nombre":"Zirconio","simbolo":"Zr","masa":"91.224","metal":"Metales de transición"},
{"noAtomico":"41","nombre":"Niobio","simbolo":"Nb","masa":"92.9064","metal":"Metales de transición"},
{"noAtomico":"42","nombre":"Molibdeno","simbolo":"Mo","masa":"95.94","metal":"Metales de transición"},
{"noAtomico":"43","nombre":"Tecnecio","simbolo":"Tc","masa":"98","metal":"Metales de transición"},
{"noAtomico":"44","nombre":"Rutenio","simbolo":"Ru","masa":"101.07","metal":"Metales de transición"},
{"noAtomico":"45","nombre":"Rodio","simbolo":"Rh","masa":"102.9055","metal":"Metales de transición"},
{"noAtomico":"46","nombre":"Paladio","simbolo":"Pd","masa":"106.42","metal":"Metales de transición"},
{"noAtomico":"47","nombre":"Plata","simbolo":"Ag","masa":"107.8682","metal":"Metales de transición"},
{"noAtomico":"48","nombre":"Cadmio","simbolo":"Cd","masa":"112.411","metal":"Metales de transición"},
{"noAtomico":"49","nombre":"Indio","simbolo":"In","masa":"114.818","metal":"Metales del bloque p"},
{"noAtomico":"50","nombre":"Estaño","simbolo":"Sn","masa":"118.71","metal":"Metales del bloque p"},
{"noAtomico":"51","nombre":"Antimonio","simbolo":"Sb","masa":"121.76","metal":"Metaloides"},
{"noAtomico":"52","nombre":"Teluro","simbolo":"Te","masa":"127.6","metal":"Metaloides"},
{"noAtomico":"53","nombre":"Yodo","simbolo":"I","masa":"126.9045","metal":"Halógenos"},
{"noAtomico":"54","nombre":"Xenón","simbolo":"Xe","masa":"131.293","metal":"Gases nobles"},
{"noAtomico":"55","nombre":"Cesio","simbolo":"Cs","masa":"132.9055","metal":"Alcalinos"},
{"noAtomico":"56","nombre":"Bario","simbolo":"Ba","masa":"137.327","metal":"Alcalinotérreos"},
{"noAtomico":"57","nombre":"Lantano","simbolo":"La","masa":"138.9055","metal":"Lantánidos"},
{"noAtomico":"58","nombre":"Cerio","simbolo":"Ce","masa":"140.116","metal":"Lantánidos"},
{"noAtomico":"59","nombre":"Praseodimio","simbolo":"Pr","masa":"140.9077","metal":"Lantánidos"},
{"noAtomico":"60","nombre":"Neodimio","simbolo":"Nd","masa":"144.24","metal":"Lantánidos"},
{"noAtomico":"61","nombre":"Promecio","simbolo":"Pm","masa":"145","metal":"Lantánidos"},
{"noAtomico":"62","nombre":"Samario","simbolo":"Sm","masa":"150.36","metal":"Lantánidos"},
{"noAtomico":"63","nombre":"Europio","simbolo":"Eu","masa":"151.964","metal":"Lantánidos"},
{"noAtomico":"64","nombre":"Gadolinio","simbolo":"Gd","masa":"157.25","metal":"Lantánidos"},
{"noAtomico":"65","nombre":"Terbio","simbolo":"Tb","masa":"158.9253","metal":"Lantánidos"},
{"noAtomico":"66","nombre":"Disprosio","simbolo":"Dy","masa":"162.5","metal":"Lantánidos"},
{"noAtomico":"67","nombre":"Holmio","simbolo":"Ho","masa":"164.9303","metal":"Lantánidos"},
{"noAtomico":"68","nombre":"Erbio","simbolo":"Er","masa":"167.259","metal":"Lantánidos"},
{"noAtomico":"69","nombre":"Tulio","simbolo":"Tm","masa":"168.9342","metal":"Lantánidos"},
{"noAtomico":"70","nombre":"Iterbio","simbolo":"Yb","masa":"173.04","metal":"Lantánidos"},
{"noAtomico":"71","nombre":"Lutecio","simbolo":"Lu","masa":"174.967","metal":"Lantánidos"},
{"noAtomico":"72","nombre":"Hafnio","simbolo":"Hf","masa":"178.49","metal":"Metales de transición"},
{"noAtomico":"73","nombre":"Tantalio","simbolo":"Ta","masa":"180.9479","metal":"Metales de transición"},
{"noAtomico":"74","nombre":"Wolframio","simbolo":"W","masa":"183.84","metal":"Metales de transición"},
{"noAtomico":"75","nombre":"Renio","simbolo":"Re","masa":"186.207","metal":"Metales de transición"},
{"noAtomico":"76","nombre":"Osmio","simbolo":"Os","masa":"190.23","metal":"Metales de transición"},
{"noAtomico":"77","nombre":"Iridio","simbolo":"Ir","masa":"192.217","metal":"Metales de transición"},
{"noAtomico":"78","nombre":"Platino","simbolo":"Pt","masa":"195.078","metal":"Metales de transición"},
{"noAtomico":"79","nombre":"Oro","simbolo":"Au","masa":"196.9665","metal":"Metales de transición"},
{"noAtomico":"80","nombre":"Mercurio","simbolo":"Hg","masa":"200.59","metal":"Metales de transición"},
{"noAtomico":"81","nombre":"Talio","simbolo":"Tl","masa":"204.3833","metal":"Metales del bloque p"},
{"noAtomico":"82","nombre":"Plomo","simbolo":"Pb","masa":"207.2","metal":"Metales del bloque p"},
{"noAtomico":"83","nombre":"Bismuto","simbolo":"Bi","masa":"208.9804","metal":"Metales del bloque p"},
{"noAtomico":"84","nombre":"Polonio","simbolo":"Po","masa":"209","metal":"Metaloides"},
{"noAtomico":"85","nombre":"Ástato","simbolo":"At","masa":"210","metal":"Halógenos"},
{"noAtomico":"86","nombre":"Radón","simbolo":"Rn","masa":"222","metal":"Gases nobles"},
{"noAtomico":"87","nombre":"Francio","simbolo":"Fr","masa":"223","metal":"Alcalinos"},
{"noAtomico":"88","nombre":"Radio","simbolo":"Ra","masa":"226","metal":"Alcalinotérreos"},
{"noAtomico":"89","nombre":"Actinio","simbolo":"Ac","masa":"227","metal":"Actínidos"},
{"noAtomico":"90","nombre":"Torio","simbolo":"Th","masa":"232.0381","metal":"Actínidos"},
{"noAtomico":"91","nombre":"Protactinio","simbolo":"Pa","masa":"231.0359","metal":"Actínidos"},
{"noAtomico":"92","nombre":"Uranio","simbolo":"U","masa":"238.0289","metal":"Actínidos"},
{"noAtomico":"93","nombre":"Neptunio","simbolo":"Np","masa":"237","metal":"Actínidos"},
{"noAtomico":"94","nombre":"Plutonio","simbolo":"Pu","masa":"244","metal":"Actínidos"},
{"noAtomico":"95","nombre":"Americio","simbolo":"Am","masa":"243","metal":"Actínidos"},
{"noAtomico":"96","nombre":"Curio","simbolo":"Cm","masa":"247","metal":"Actínidos"},
{"noAtomico":"97","nombre":"Berkelio","simbolo":"Bk","masa":"247","metal":"Actínidos"},
{"noAtomico":"98","nombre":"Californio","simbolo":"Cf","masa":"251","metal":"Actínidos"},
{"noAtomico":"99","nombre":"Einstenio","simbolo":"Es","masa":"252","metal":"Actínidos"},
{"noAtomico":"100","nombre":"Fermio","simbolo":"Fm","masa":"257","metal":"Actínidos"},
{"noAtomico":"101","nombre":"Mendelevio","simbolo":"Md","masa":"258","metal":"Actínidos"},
{"noAtomico":"102","nombre":"Nobelio","simbolo":"No","masa":"259","metal":"Actínidos"},
{"noAtomico":"103","nombre":"Lawrencio","simbolo":"Lr","masa":"262","metal":"Actínidos"},
{"noAtomico":"104","nombre":"Rutherfordio","simbolo":"Rf","masa":"267","metal":"Metales de transición"},
{"noAtomico":"105","nombre":"Dubnio","simbolo":"Db","masa":"268","metal":"Metales de transición"},
{"noAtomico":"106","nombre":"Seaborgio","simbolo":"Sg","masa":"271","metal":"Metales de transición"},
{"noAtomico":"107","nombre":"Bohrio","simbolo":"Bh","masa":"272","metal":"Metales de transición"},
{"noAtomico":"108","nombre":"Hassio","simbolo":"Hs","masa":"277","metal":"Metales de transición"},
{"noAtomico":"109","nombre":"Meitnerio","simbolo":"Mt","masa":"276","metal":"Metales de transición"},
{"noAtomico":"110","nombre":"Darmstadio","simbolo":"Ds","masa":"281","metal":"Metales de transición"},
{"noAtomico":"111","nombre":"Ununio","simbolo":"Uuu","masa":"280","metal":"Metales de transición"},
{"noAtomico":"112","nombre":"Ununbio","simbolo":"Uub","masa":"285","metal":"Metales de transición"},
{"noAtomico":"113","nombre":"Ununtrio","simbolo":"Uut","masa":"284","metal":"Metales del bloque p"},
{"noAtomico":"114","nombre":"Ununquadio","simbolo":"Uuq","masa":"289","metal":"Metales del bloque p"},
{"noAtomico":"115","nombre":"Ununpentio","simbolo":"Uup","masa":"288","metal":"Metales del bloque p"},
{"noAtomico":"116","nombre":"Ununhexio","simbolo":"Uuh","masa":"293","metal":"Metales del bloque p"},
{"noAtomico":"117","nombre":"Ununseptio","simbolo":"Uus","masa":"294","metal":"Halógenos"},
{"noAtomico":"118","nombre":"Ununoctio","simbolo":"Uuo","masa":"294","metal":"Gases nobles"}
]

